version: '3'
services:
  frontend:
    image: leones/frontend
    build: ./frontend
    container_name: frontend
    links:
      - backend
    ports:
      - '4200:80'
    depends_on:
      - backend

  db:
    image: leones/db
    build: ./db
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example

  backend:
    image: leones/backend
    build: ./backend
    container_name: backend
    ports:
      - '3000:3000'
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=example

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres
      PGADMIN_DEFAULT_PASSWORD: example
    ports:
      - 5050:80
    container_name: pgadmin
